### ISSUE TITLE
Add specification for metadata.annotations map

### ISSUE THREAD

**Issue by astromechza** [score-spec/schema#16]
Just like resources have metadata.annotations today, there is need to support the same concept formally on the workload metadata as well. This will allow us to pass kubernetes-style annotations through to the destination runtime. 

For score-compose, these would be labels, while for score-helm and score-humanitec these would be annotations on the final deployment objects. Since this is just metadata it can also be ignored without affecting the functionality of the workload.

```
metadata:
  name: my workload
  annotations:
    example.com/my-annotation: value
```

This should carry the same specification as resource.metadata.annotations.
